import type { ConsoleDomain, ConsoleMenuItem } from '@/types/console'

const domainTitles: Record<ConsoleDomain, string> = {
  workbench: 'Workbench',
  system: 'System Management',
  online: 'Online Low-Code',
  ai: 'AI Platform',
  analytics: 'Reporting and Screens',
  ops: 'Messaging and Operations',
  showcase: 'Showcase',
  advanced: 'Advanced Features',
  enterprise: 'Enterprise Enhancements',
}

export const fallbackConsoleMenuTree: ConsoleMenuItem[] = [
  {
    id: 'workbench-home',
    code: 'menu:workbench:home',
    title: 'Workbench',
    route: '/workbench',
    domain: 'workbench',
    children: [],
  },
  {
    id: 'system-home',
    code: 'menu:system:home',
    title: 'System Management',
    route: '/system',
    domain: 'system',
    children: [
      {
        id: 'system-users',
        code: 'menu:system:users',
        title: 'Users',
        route: '/system/users',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-roles',
        code: 'menu:system:roles',
        title: 'Roles',
        route: '/system/roles',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-menus',
        code: 'menu:system:menus',
        title: 'Menus',
        route: '/system/menus',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-buttons',
        code: 'menu:system:buttons',
        title: 'Button Permissions',
        route: '/system/buttons',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-data-rules',
        code: 'menu:system:data-rules',
        title: 'Data Rules',
        route: '/system/data-rules',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-form-permissions',
        code: 'menu:system:form-permissions',
        title: 'Form Permissions',
        route: '/system/form-permissions',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-departments',
        code: 'menu:system:departments',
        title: 'Departments',
        route: '/system/departments',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-my-departments',
        code: 'menu:system:my-departments',
        title: 'My Departments',
        route: '/system/my-departments',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-dictionaries',
        code: 'menu:system:dictionaries',
        title: 'Dictionaries',
        route: '/system/dictionaries',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-dictionary-categories',
        code: 'menu:system:dictionary-categories',
        title: 'Dictionary Categories',
        route: '/system/dictionary-categories',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-notices',
        code: 'menu:system:notices',
        title: 'Notices',
        route: '/system/notices',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-positions',
        code: 'menu:system:positions',
        title: 'Positions',
        route: '/system/positions',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-contacts',
        code: 'menu:system:contacts',
        title: 'Contacts',
        route: '/system/contacts',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-data-sources',
        code: 'menu:system:data-sources',
        title: 'Data Sources',
        route: '/system/data-sources',
        domain: 'system',
        children: [],
      },
      {
        id: 'system-tenants',
        code: 'menu:system:tenants',
        title: 'Tenant Management',
        route: '/system/tenants',
        domain: 'system',
        children: [],
      },
    ],
  },
  {
    id: 'online-home',
    code: 'menu:online:home',
    title: 'Online Low-Code',
    route: '/online',
    domain: 'online',
    children: [
      {
        id: 'online-forms',
        code: 'menu:online:forms',
        title: 'Online Forms',
        route: '/online/forms',
        domain: 'online',
        children: [],
      },
      {
        id: 'online-reports',
        code: 'menu:online:reports',
        title: 'Online Reports',
        route: '/online/reports',
        domain: 'online',
        children: [],
      },
      {
        id: 'online-codegen',
        code: 'menu:online:codegen',
        title: 'Online Code Generator',
        route: '/online/codegen',
        domain: 'online',
        children: [],
      },
      {
        id: 'online-dashboards',
        code: 'menu:online:dashboards',
        title: 'Online Dashboards',
        route: '/online/dashboards',
        domain: 'online',
        children: [],
      },
      {
        id: 'online-naming-rules',
        code: 'menu:online:naming-rules',
        title: 'Online Naming Rules',
        route: '/online/naming-rules',
        domain: 'online',
        children: [],
      },
      {
        id: 'online-validation-rules',
        code: 'menu:online:validation-rules',
        title: 'Online Validation Rules',
        route: '/online/validation-rules',
        domain: 'online',
        children: [],
      },
    ],
  },
  {
    id: 'ai-home',
    code: 'menu:ai:home',
    title: 'AI Platform',
    route: '/ai',
    domain: 'ai',
    children: [
      { id: 'ai-models', code: 'menu:ai:models', title: 'Model Management', route: '/ai/models', domain: 'ai', children: [] },
      { id: 'ai-assistant', code: 'menu:ai:assistant', title: 'AI Assistant', route: '/ai/assistant', domain: 'ai', children: [] },
      { id: 'ai-generation', code: 'menu:ai:generation', title: 'AI Generation', route: '/ai/generation', domain: 'ai', children: [] },
      { id: 'ai-ocr', code: 'menu:ai:ocr', title: 'OCR Samples', route: '/ai/ocr', domain: 'ai', children: [] },
      { id: 'ai-knowledge', code: 'menu:ai:knowledge', title: 'Knowledge Q&A', route: '/ai/knowledge', domain: 'ai', children: [] },
      { id: 'ai-workflows', code: 'menu:ai:workflows', title: 'AI Workflows', route: '/ai/workflows', domain: 'ai', children: [] },
      { id: 'ai-image-chat', code: 'menu:ai:image-chat', title: 'Image Chat', route: '/ai/image-chat', domain: 'ai', children: [] },
      { id: 'ai-embed', code: 'menu:ai:embed', title: 'Embedded Chat', route: '/ai/embed', domain: 'ai', children: [] },
      { id: 'ai-mobile', code: 'menu:ai:mobile', title: 'Mobile Chat', route: '/ai/mobile', domain: 'ai', children: [] },
    ],
  },
]

export function getConsoleDomainTitle(domain: ConsoleDomain): string {
  return domainTitles[domain]
}
