/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AICopilotPanel: typeof import('./../components/copilot/AICopilotPanel.vue')['default']
    BpmnViewer: typeof import('./../components/workflow/BpmnViewer.vue')['default']
    DataTable: typeof import('./../components/data/DataTable.vue')['default']
    DynamicForm: typeof import('./../components/form/DynamicForm.vue')['default']
    FormFieldRenderer: typeof import('./../components/form/FormFieldRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
