/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AiModelConfigView': RouteRecordInfo<'/AiModelConfigView', '/AiModelConfigView', Record<never, never>, Record<never, never>>,
    '/DashboardView': RouteRecordInfo<'/DashboardView', '/DashboardView', Record<never, never>, Record<never, never>>,
    '/FormsView': RouteRecordInfo<'/FormsView', '/FormsView', Record<never, never>, Record<never, never>>,
    '/GenerateView': RouteRecordInfo<'/GenerateView', '/GenerateView', Record<never, never>, Record<never, never>>,
    '/LayoutView': RouteRecordInfo<'/LayoutView', '/LayoutView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/ReportsView': RouteRecordInfo<'/ReportsView', '/ReportsView', Record<never, never>, Record<never, never>>,
    '/SettingsView': RouteRecordInfo<'/SettingsView', '/SettingsView', Record<never, never>, Record<never, never>>,
    '/SystemButtonsView': RouteRecordInfo<'/SystemButtonsView', '/SystemButtonsView', Record<never, never>, Record<never, never>>,
    '/SystemDataRulesView': RouteRecordInfo<'/SystemDataRulesView', '/SystemDataRulesView', Record<never, never>, Record<never, never>>,
    '/SystemMenusView': RouteRecordInfo<'/SystemMenusView', '/SystemMenusView', Record<never, never>, Record<never, never>>,
    '/SystemRolesView': RouteRecordInfo<'/SystemRolesView', '/SystemRolesView', Record<never, never>, Record<never, never>>,
    '/SystemUsersView': RouteRecordInfo<'/SystemUsersView', '/SystemUsersView', Record<never, never>, Record<never, never>>,
    '/WorkflowsView': RouteRecordInfo<'/WorkflowsView', '/WorkflowsView', Record<never, never>, Record<never, never>>,
  }
}
