/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/ai/AiPlatformHomeView': RouteRecordInfo<'/ai/AiPlatformHomeView', '/ai/AiPlatformHomeView', Record<never, never>, Record<never, never>>,
    '/ai/assistant/AiAssistantView': RouteRecordInfo<'/ai/assistant/AiAssistantView', '/ai/assistant/AiAssistantView', Record<never, never>, Record<never, never>>,
    '/ai/embed/AiEmbeddedChatView': RouteRecordInfo<'/ai/embed/AiEmbeddedChatView', '/ai/embed/AiEmbeddedChatView', Record<never, never>, Record<never, never>>,
    '/ai/generation/AiGenerationView': RouteRecordInfo<'/ai/generation/AiGenerationView', '/ai/generation/AiGenerationView', Record<never, never>, Record<never, never>>,
    '/ai/image-chat/AiImageChatView': RouteRecordInfo<'/ai/image-chat/AiImageChatView', '/ai/image-chat/AiImageChatView', Record<never, never>, Record<never, never>>,
    '/ai/knowledge/AiKnowledgeView': RouteRecordInfo<'/ai/knowledge/AiKnowledgeView', '/ai/knowledge/AiKnowledgeView', Record<never, never>, Record<never, never>>,
    '/ai/mobile/AiMobileChatView': RouteRecordInfo<'/ai/mobile/AiMobileChatView', '/ai/mobile/AiMobileChatView', Record<never, never>, Record<never, never>>,
    '/ai/ocr/AiOcrView': RouteRecordInfo<'/ai/ocr/AiOcrView', '/ai/ocr/AiOcrView', Record<never, never>, Record<never, never>>,
    '/ai/workflows/AiWorkflowsView': RouteRecordInfo<'/ai/workflows/AiWorkflowsView', '/ai/workflows/AiWorkflowsView', Record<never, never>, Record<never, never>>,
    '/AiModelConfigView': RouteRecordInfo<'/AiModelConfigView', '/AiModelConfigView', Record<never, never>, Record<never, never>>,
    '/DashboardView': RouteRecordInfo<'/DashboardView', '/DashboardView', Record<never, never>, Record<never, never>>,
    '/FormsView': RouteRecordInfo<'/FormsView', '/FormsView', Record<never, never>, Record<never, never>>,
    '/GenerateView': RouteRecordInfo<'/GenerateView', '/GenerateView', Record<never, never>, Record<never, never>>,
    '/LayoutView': RouteRecordInfo<'/LayoutView', '/LayoutView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/online/codegen/OnlineCodeGeneratorView': RouteRecordInfo<'/online/codegen/OnlineCodeGeneratorView', '/online/codegen/OnlineCodeGeneratorView', Record<never, never>, Record<never, never>>,
    '/online/dashboards/OnlineDashboardsView': RouteRecordInfo<'/online/dashboards/OnlineDashboardsView', '/online/dashboards/OnlineDashboardsView', Record<never, never>, Record<never, never>>,
    '/online/forms/OnlineFormsView': RouteRecordInfo<'/online/forms/OnlineFormsView', '/online/forms/OnlineFormsView', Record<never, never>, Record<never, never>>,
    '/online/naming-rules/OnlineNamingRulesView': RouteRecordInfo<'/online/naming-rules/OnlineNamingRulesView', '/online/naming-rules/OnlineNamingRulesView', Record<never, never>, Record<never, never>>,
    '/online/OnlineHomeView': RouteRecordInfo<'/online/OnlineHomeView', '/online/OnlineHomeView', Record<never, never>, Record<never, never>>,
    '/online/reports/OnlineReportsView': RouteRecordInfo<'/online/reports/OnlineReportsView', '/online/reports/OnlineReportsView', Record<never, never>, Record<never, never>>,
    '/online/validation-rules/OnlineValidationRulesView': RouteRecordInfo<'/online/validation-rules/OnlineValidationRulesView', '/online/validation-rules/OnlineValidationRulesView', Record<never, never>, Record<never, never>>,
    '/ReportsView': RouteRecordInfo<'/ReportsView', '/ReportsView', Record<never, never>, Record<never, never>>,
    '/SettingsView': RouteRecordInfo<'/SettingsView', '/SettingsView', Record<never, never>, Record<never, never>>,
    '/system/buttons/SystemButtonPermissionsView': RouteRecordInfo<'/system/buttons/SystemButtonPermissionsView', '/system/buttons/SystemButtonPermissionsView', Record<never, never>, Record<never, never>>,
    '/system/contacts/SystemContactsView': RouteRecordInfo<'/system/contacts/SystemContactsView', '/system/contacts/SystemContactsView', Record<never, never>, Record<never, never>>,
    '/system/data-rules/SystemDataPermissionRulesView': RouteRecordInfo<'/system/data-rules/SystemDataPermissionRulesView', '/system/data-rules/SystemDataPermissionRulesView', Record<never, never>, Record<never, never>>,
    '/system/data-sources/SystemDataSourcesView': RouteRecordInfo<'/system/data-sources/SystemDataSourcesView', '/system/data-sources/SystemDataSourcesView', Record<never, never>, Record<never, never>>,
    '/system/departments/SystemDepartmentsView': RouteRecordInfo<'/system/departments/SystemDepartmentsView', '/system/departments/SystemDepartmentsView', Record<never, never>, Record<never, never>>,
    '/system/dictionaries/SystemDictionariesView': RouteRecordInfo<'/system/dictionaries/SystemDictionariesView', '/system/dictionaries/SystemDictionariesView', Record<never, never>, Record<never, never>>,
    '/system/dictionary-categories/SystemDictionaryCategoriesView': RouteRecordInfo<'/system/dictionary-categories/SystemDictionaryCategoriesView', '/system/dictionary-categories/SystemDictionaryCategoriesView', Record<never, never>, Record<never, never>>,
    '/system/form-permissions/SystemFormPermissionsView': RouteRecordInfo<'/system/form-permissions/SystemFormPermissionsView', '/system/form-permissions/SystemFormPermissionsView', Record<never, never>, Record<never, never>>,
    '/system/menus/SystemMenusListView': RouteRecordInfo<'/system/menus/SystemMenusListView', '/system/menus/SystemMenusListView', Record<never, never>, Record<never, never>>,
    '/system/my-departments/MyDepartmentsView': RouteRecordInfo<'/system/my-departments/MyDepartmentsView', '/system/my-departments/MyDepartmentsView', Record<never, never>, Record<never, never>>,
    '/system/notices/SystemNoticesView': RouteRecordInfo<'/system/notices/SystemNoticesView', '/system/notices/SystemNoticesView', Record<never, never>, Record<never, never>>,
    '/system/positions/SystemPositionsView': RouteRecordInfo<'/system/positions/SystemPositionsView', '/system/positions/SystemPositionsView', Record<never, never>, Record<never, never>>,
    '/system/roles/SystemRolesListView': RouteRecordInfo<'/system/roles/SystemRolesListView', '/system/roles/SystemRolesListView', Record<never, never>, Record<never, never>>,
    '/system/SystemHomeView': RouteRecordInfo<'/system/SystemHomeView', '/system/SystemHomeView', Record<never, never>, Record<never, never>>,
    '/system/tenants/SystemTenantsView': RouteRecordInfo<'/system/tenants/SystemTenantsView', '/system/tenants/SystemTenantsView', Record<never, never>, Record<never, never>>,
    '/system/users/SystemUsersListView': RouteRecordInfo<'/system/users/SystemUsersListView', '/system/users/SystemUsersListView', Record<never, never>, Record<never, never>>,
    '/SystemButtonsView': RouteRecordInfo<'/SystemButtonsView', '/SystemButtonsView', Record<never, never>, Record<never, never>>,
    '/SystemDataRulesView': RouteRecordInfo<'/SystemDataRulesView', '/SystemDataRulesView', Record<never, never>, Record<never, never>>,
    '/SystemMenusView': RouteRecordInfo<'/SystemMenusView', '/SystemMenusView', Record<never, never>, Record<never, never>>,
    '/SystemRolesView': RouteRecordInfo<'/SystemRolesView', '/SystemRolesView', Record<never, never>, Record<never, never>>,
    '/SystemUsersView': RouteRecordInfo<'/SystemUsersView', '/SystemUsersView', Record<never, never>, Record<never, never>>,
    '/workbench/WorkbenchHomeView': RouteRecordInfo<'/workbench/WorkbenchHomeView', '/workbench/WorkbenchHomeView', Record<never, never>, Record<never, never>>,
    '/WorkflowsView': RouteRecordInfo<'/WorkflowsView', '/WorkflowsView', Record<never, never>, Record<never, never>>,
  }
}
